
name: Set output
run: echo "{name}={value}" >> $GITHUB_OUTPUT

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
      

name: Save state



